### ISSUE TITLE
Roadmap to V1

### ISSUE THREAD

**Issue by kangarko** [kangarko/docs#2]
- [x] Go to https://github.com/kangarko/docs
- [x] Take all Egehan's bot stuff out
- [x] Insert your docs page
- [x] Move back Egehan's bot stuff into your pages, as a Bot section
- [x] Keep Egehan's theme and plugin's settings
- [x] Model the homepage and the top nav menu links like https://docs.papermc.io/ has

**Comment by kangarko** [comment]
@EgehanKilicarslan and @BouncingSquirrel

**Comment by BouncingSquirrel** [comment]
- [ ] Find a way to embed PDFs

**Comment by BouncingSquirrel** [comment]
@kangarko and @EgehanKilicarslan,
Please verify the changes I made. Egehan, I had to remove your navigation and move it into the sidebar. That's why I showed the navigation sidebar on "Getting Started" again. I also added some nice Emojis. Here are some thoughts I had along the way:
- On MineBot Home page, rename "Get Started" to "Getting Started"?
- Remove TOC on Changelog?
- "Examples" has two different icons!
- Make default dark theme?
- Add "Documentation Blog"?

**Comment by kangarko** [comment]
Thanks, checking in 24 hours

**Comment by kangarko** [comment]
> On MineBot Home page, rename "Get Started" to "Getting Started"?
 lets keep Get Started

> Remove TOC on Changelog?
What is TOC? Lets remove changelog page altogether

"Examples" has two different icons!
> thanks for fixing

Make default dark theme?
> Make default the system theme please

> White favicon looks bad on white browsers.
It's okay for now thanks for noticing

> Add an Miscellanous documentation?
> Add a README?
> Add "Documentation Blog"?
No need.

Thank you!
